// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNuuB1__TRZ4vqna6t-F3O5Sao2vW-9MY',
    appId: '1:616607384091:web:c0a7c83e3fb98d08252ebe',
    messagingSenderId: '616607384091',
    projectId: 'diaryfcm-329ad',
    authDomain: 'diaryfcm-329ad.firebaseapp.com',
    storageBucket: 'diaryfcm-329ad.firebasestorage.app',
    measurementId: 'G-3YGMFLB2XB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyqR6c0tJq_Kg8kx8DiBKIgR34zJVPX-8',
    appId: '1:616607384091:android:59c990932db74cff252ebe',
    messagingSenderId: '616607384091',
    projectId: 'diaryfcm-329ad',
    storageBucket: 'diaryfcm-329ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1UHbzF96hgtscuA8p3-4UrztvUpQBNh0',
    appId: '1:616607384091:ios:b1cc3b0007e981c9252ebe',
    messagingSenderId: '616607384091',
    projectId: 'diaryfcm-329ad',
    storageBucket: 'diaryfcm-329ad.firebasestorage.app',
    iosBundleId: 'com.example.stickyDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1UHbzF96hgtscuA8p3-4UrztvUpQBNh0',
    appId: '1:616607384091:ios:b1cc3b0007e981c9252ebe',
    messagingSenderId: '616607384091',
    projectId: 'diaryfcm-329ad',
    storageBucket: 'diaryfcm-329ad.firebasestorage.app',
    iosBundleId: 'com.example.stickyDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNuuB1__TRZ4vqna6t-F3O5Sao2vW-9MY',
    appId: '1:616607384091:web:135a6bdef3962c68252ebe',
    messagingSenderId: '616607384091',
    projectId: 'diaryfcm-329ad',
    authDomain: 'diaryfcm-329ad.firebaseapp.com',
    storageBucket: 'diaryfcm-329ad.firebasestorage.app',
    measurementId: 'G-CR8JLE9CQH',
  );
}
