name: Diary
description: "Diary that helps you build habit."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0
  intl: ^0.20.2
  logger: ^2.5.0
  rxdart: ^0.28.0
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
